# -*- coding: utf-8 -*-
from enums import CardType, ClassType, EffectType, ProcessType, TargetType, TribeType
from card_data import CardData

BASIC_CARD_DATABASE = {
    "Indomitable Fighter": CardData(card_id='Indomitable Fighter', name='Indomitable Fighter', ...),
    "Leah, Bellringer Angel": CardData(card_id='Leah, Bellringer Angel', name='Leah, Bellringer Angel', ...),
    "Quake Goliath": CardData(card_id='Quake Goliath', name='Quake Goliath', ...),
    "Detective's Lens": CardData(card_id='Detective's Lens', name='Detective's Lens', ...),
    "Arriet, Luxminstrel": CardData(card_id='Arriet, Luxminstrel', name='Arriet, Luxminstrel', ...),
    "Caravan Mammoth": CardData(card_id='Caravan Mammoth', name='Caravan Mammoth', ...),
    "Adventurers' Guild": CardData(card_id='Adventurers' Guild', name='Adventurers' Guild', ...),
    "Fairy Tamer": CardData(card_id='Fairy Tamer', name='Fairy Tamer', ...),
    "Stray Beastman": CardData(card_id='Stray Beastman', name='Stray Beastman', ...),
    "Gentle Treant": CardData(card_id='Gentle Treant', name='Gentle Treant', ...),
    "Wild Profusion": CardData(card_id='Wild Profusion', name='Wild Profusion', ...),
    "May, Journey Elf": CardData(card_id='May, Journey Elf', name='May, Journey Elf', ...),
    "Selwyn, Sonic Archer": CardData(card_id='Selwyn, Sonic Archer', name='Selwyn, Sonic Archer', ...),
    "Bug Alert": CardData(card_id='Bug Alert', name='Bug Alert', ...),
    "Flashstep Quickblader": CardData(card_id='Flashstep Quickblader', name='Flashstep Quickblader', ...),
    "Arms Peddler": CardData(card_id='Arms Peddler', name='Arms Peddler', ...),
    "Centaur Centurion": CardData(card_id='Centaur Centurion', name='Centaur Centurion', ...),
    "Way of the Maid": CardData(card_id='Way of the Maid', name='Way of the Maid', ...),
    "Royal Coachwoman": CardData(card_id='Royal Coachwoman', name='Royal Coachwoman', ...),
    "Rusty, Luxcard Trickster": CardData(card_id='Rusty, Luxcard Trickster', name='Rusty, Luxcard Trickster', ...),
    "Ancestral Crown": CardData(card_id='Ancestral Crown', name='Ancestral Crown', ...),
    "Dazzling Runeknight": CardData(card_id='Dazzling Runeknight', name='Dazzling Runeknight', ...),
    "Witch's New Brew": CardData(card_id='Witch's New Brew', name='Witch's New Brew', ...),
    "Foresight": CardData(card_id='Foresight', name='Foresight', ...),
    "Truth Summons": CardData(card_id='Truth Summons', name='Truth Summons', ...),
    "Remi & Rami, Two-Faced Witch": CardData(card_id='Remi & Rami, Two-Faced Witch', name='Remi & Rami, Two-Faced Witch', ...),
    "Blaze Destroyer": CardData(card_id='Blaze Destroyer', name='Blaze Destroyer', ...),
    "Arcane Eruption": CardData(card_id='Arcane Eruption', name='Arcane Eruption', ...),
    "Searing Firenewt": CardData(card_id='Searing Firenewt', name='Searing Firenewt', ...),
    "Axe-Wielding Dragonslayer": CardData(card_id='Axe-Wielding Dragonslayer', name='Axe-Wielding Dragonslayer', ...),
    "Warrior of the Deep": CardData(card_id='Warrior of the Deep', name='Warrior of the Deep', ...),
    "Strike of the Dragonewt": CardData(card_id='Strike of the Dragonewt', name='Strike of the Dragonewt', ...),
    "Draconic Berserker": CardData(card_id='Draconic Berserker', name='Draconic Berserker', ...),
    "Battleforged Dragon Keeper": CardData(card_id='Battleforged Dragon Keeper', name='Battleforged Dragon Keeper', ...),
    "Dragonsign": CardData(card_id='Dragonsign', name='Dragonsign', ...),
    "Mistress of the Fanged": CardData(card_id='Mistress of the Fanged', name='Mistress of the Fanged', ...),
    "Night Fiend": CardData(card_id='Night Fiend', name='Night Fiend', ...),
    "Devious Lesser Mummy": CardData(card_id='Devious Lesser Mummy', name='Devious Lesser Mummy', ...),
    "Chaos Cyclone": CardData(card_id='Chaos Cyclone', name='Chaos Cyclone', ...),
    "Lilith, Enchanting Succubus": CardData(card_id='Lilith, Enchanting Succubus', name='Lilith, Enchanting Succubus', ...),
    "Amorous Necromancer": CardData(card_id='Amorous Necromancer', name='Amorous Necromancer', ...),
    "Soul Predation": CardData(card_id='Soul Predation', name='Soul Predation', ...),
    "Soulcure Sister": CardData(card_id='Soulcure Sister', name='Soulcure Sister', ...),
    "Fox of Purity": CardData(card_id='Fox of Purity', name='Fox of Purity', ...),
    "Winged Warrior": CardData(card_id='Winged Warrior', name='Winged Warrior', ...),
    "Avian Statue": CardData(card_id='Avian Statue', name='Avian Statue', ...),
    "Ironfist Priest": CardData(card_id='Ironfist Priest', name='Ironfist Priest', ...),
    "Sacred Griffon": CardData(card_id='Sacred Griffon', name='Sacred Griffon', ...),
    "Winged Statue": CardData(card_id='Winged Statue', name='Winged Statue', ...),
    "Kitty Cannoneer": CardData(card_id='Kitty Cannoneer', name='Kitty Cannoneer', ...),
    "Puppet Lancer": CardData(card_id='Puppet Lancer', name='Puppet Lancer', ...),
    "Mechanized Beast": CardData(card_id='Mechanized Beast', name='Mechanized Beast', ...),
    "Bullet from Beyond": CardData(card_id='Bullet from Beyond', name='Bullet from Beyond', ...),
    "Electric Whip Lass": CardData(card_id='Electric Whip Lass', name='Electric Whip Lass', ...),
    "Mecha Cavalier": CardData(card_id='Mecha Cavalier', name='Mecha Cavalier', ...),
    "Puppet Theater": CardData(card_id='Puppet Theater', name='Puppet Theater', ...),
}

LEGENDS_RISE_CARD_DATABASE = {
    "Ruby, Greedy Cherub": CardData(card_id='Ruby, Greedy Cherub', name='Ruby, Greedy Cherub', ...),
    "Vigilant Detective": CardData(card_id='Vigilant Detective', name='Vigilant Detective', ...),
    "Goblin Foray": CardData(card_id='Goblin Foray', name='Goblin Foray', ...),
    "Apollo, Heaven's Envoy": CardData(card_id='Apollo, Heaven's Envoy', name='Apollo, Heaven's Envoy', ...),
    "Seraphic Tidings": CardData(card_id='Seraphic Tidings', name='Seraphic Tidings', ...),
    "Phildau, Lionheart Ward": CardData(card_id='Phildau, Lionheart Ward', name='Phildau, Lionheart Ward', ...),
    "Divine Thunder": CardData(card_id='Divine Thunder', name='Divine Thunder', ...),
    "Olivia, Heroic Dark Angel": CardData(card_id='Olivia, Heroic Dark Angel', name='Olivia, Heroic Dark Angel', ...),
    "Ruler of Cocytus": CardData(card_id='Ruler of Cocytus', name='Ruler of Cocytus', ...),
    "Fay Twinkletoes": CardData(card_id='Fay Twinkletoes', name='Fay Twinkletoes', ...),
    "Capricious Sprite": CardData(card_id='Capricious Sprite', name='Capricious Sprite', ...),
    "Deepwood Fairy Beast": CardData(card_id='Deepwood Fairy Beast', name='Deepwood Fairy Beast', ...),
    "Workin' Grasshopper": CardData(card_id='Workin' Grasshopper', name='Workin' Grasshopper', ...),
    "Elder Sagebrush": CardData(card_id='Elder Sagebrush', name='Elder Sagebrush', ...),
    "Fairy Convocation": CardData(card_id='Fairy Convocation', name='Fairy Convocation', ...),
    "Aerin, Crystalian Frostward": CardData(card_id='Aerin, Crystalian Frostward', name='Aerin, Crystalian Frostward', ...),
    "Good Fairy of the Pond": CardData(card_id='Good Fairy of the Pond', name='Good Fairy of the Pond', ...),
    "Baby Carbuncle": CardData(card_id='Baby Carbuncle', name='Baby Carbuncle', ...),
    "Lambent Cairn": CardData(card_id='Lambent Cairn', name='Lambent Cairn', ...),
    "Fragrantwood Whispers": CardData(card_id='Fragrantwood Whispers', name='Fragrantwood Whispers', ...),
    "Lily, Crystalian Innocence": CardData(card_id='Lily, Crystalian Innocence', name='Lily, Crystalian Innocence', ...),
    "Glade, Fragrantwood Ward": CardData(card_id='Glade, Fragrantwood Ward', name='Glade, Fragrantwood Ward', ...),
    "Bayle, Luxglaive Warrior": CardData(card_id='Bayle, Luxglaive Warrior', name='Bayle, Luxglaive Warrior', ...),
    "Killer Rhinoceroach": CardData(card_id='Killer Rhinoceroach', name='Killer Rhinoceroach', ...),
    "Godwood Staff": CardData(card_id='Godwood Staff', name='Godwood Staff', ...),
    "Aria, Lady of the Woods": CardData(card_id='Aria, Lady of the Woods', name='Aria, Lady of the Woods', ...),
    "Opulent Rose Queen": CardData(card_id='Opulent Rose Queen', name='Opulent Rose Queen', ...),
    "Amataz, Origin Blader": CardData(card_id='Amataz, Origin Blader', name='Amataz, Origin Blader', ...),
    "Ian, Lovebound Knight": CardData(card_id='Ian, Lovebound Knight', name='Ian, Lovebound Knight', ...),
    "Ernesta, Peace Hawker": CardData(card_id='Ernesta, Peace Hawker', name='Ernesta, Peace Hawker', ...),
    "Lyrala, Luminous Potionwright": CardData(card_id='Lyrala, Luminous Potionwright', name='Lyrala, Luminous Potionwright', ...),
    "Hound of War": CardData(card_id='Hound of War', name='Hound of War', ...),
    "Ignominious Samurai": CardData(card_id='Ignominious Samurai', name='Ignominious Samurai', ...),
    "Knightly Rending": CardData(card_id='Knightly Rending', name='Knightly Rending', ...),
    "Luminous Commander": CardData(card_id='Luminous Commander', name='Luminous Commander', ...),
    "Luminous Magus": CardData(card_id='Luminous Magus', name='Luminous Magus', ...),
    "Luminous Lancetrooper": CardData(card_id='Luminous Lancetrooper', name='Luminous Lancetrooper', ...),
    "Shinobi Squirrel": CardData(card_id='Shinobi Squirrel', name='Shinobi Squirrel', ...),
    "Ironcrown Majesty": CardData(card_id='Ironcrown Majesty', name='Ironcrown Majesty', ...),
    "Jeno, Levin Axeraider": CardData(card_id='Jeno, Levin Axeraider', name='Jeno, Levin Axeraider', ...),
    "Valse, Silent Sniper": CardData(card_id='Valse, Silent Sniper', name='Valse, Silent Sniper', ...),
    "Zirconia, Ironcrown Ward": CardData(card_id='Zirconia, Ironcrown Ward', name='Zirconia, Ironcrown Ward', ...),
    "Amalia, Luxsteel Paladin": CardData(card_id='Amalia, Luxsteel Paladin', name='Amalia, Luxsteel Paladin', ...),
    "Ravening Tentacles": CardData(card_id='Ravening Tentacles', name='Ravening Tentacles', ...),
    "Albert, Levin Stormsaber": CardData(card_id='Albert, Levin Stormsaber', name='Albert, Levin Stormsaber', ...),
    "Amelia, Silver Captain": CardData(card_id='Amelia, Silver Captain', name='Amelia, Silver Captain', ...),
    "Kagemitsu, Enduring Warrior": CardData(card_id='Kagemitsu, Enduring Warrior', name='Kagemitsu, Enduring Warrior', ...),
    "Runeblade Conductor": CardData(card_id='Runeblade Conductor', name='Runeblade Conductor', ...),
    "Apprentice Astrologer": CardData(card_id='Apprentice Astrologer', name='Apprentice Astrologer', ...),
    "Owl Summoner": CardData(card_id='Owl Summoner', name='Owl Summoner', ...),
    "Starry-Eyed Penguin Wizard": CardData(card_id='Starry-Eyed Penguin Wizard', name='Starry-Eyed Penguin Wizard', ...),
    "Radiant Rainbow": CardData(card_id='Radiant Rainbow', name='Radiant Rainbow', ...),
    "Stormy Blast": CardData(card_id='Stormy Blast', name='Stormy Blast', ...),
    "Ms. Miranda, Adored Academic": CardData(card_id='Ms. Miranda, Adored Academic', name='Ms. Miranda, Adored Academic', ...),
    "Emmylou, Witch of Wonder": CardData(card_id='Emmylou, Witch of Wonder', name='Emmylou, Witch of Wonder', ...),
    "William, Mysterian Student": CardData(card_id='William, Mysterian Student', name='William, Mysterian Student', ...),
    "Sagelight Teachings": CardData(card_id='Sagelight Teachings', name='Sagelight Teachings', ...),
    "Snowman Army": CardData(card_id='Snowman Army', name='Snowman Army', ...),
    "Juno, Visionary Alchemist": CardData(card_id='Juno, Visionary Alchemist', name='Juno, Visionary Alchemist', ...),
    "Penelope, Potions Prodigy": CardData(card_id='Penelope, Potions Prodigy', name='Penelope, Potions Prodigy', ...),
    "Edelweiss, Sagelight Ward": CardData(card_id='Edelweiss, Sagelight Ward', name='Edelweiss, Sagelight Ward', ...),
    "Homework Time!": CardData(card_id='Homework Time!', name='Homework Time!', ...),
    "Demonic Call": CardData(card_id='Demonic Call', name='Demonic Call', ...),
    "Kuon, Fivefold Master": CardData(card_id='Kuon, Fivefold Master', name='Kuon, Fivefold Master', ...),
    "Anne & Grea, Mysterian Duo": CardData(card_id='Anne & Grea, Mysterian Duo', name='Anne & Grea, Mysterian Duo', ...),
    "Dimension Climb": CardData(card_id='Dimension Climb', name='Dimension Climb', ...),
    "Silvercloud Dragonrider": CardData(card_id='Silvercloud Dragonrider', name='Silvercloud Dragonrider', ...),
    "Swordsnout Trencher": CardData(card_id='Swordsnout Trencher', name='Swordsnout Trencher', ...),
    "Fledgling Dragonslayer": CardData(card_id='Fledgling Dragonslayer', name='Fledgling Dragonslayer', ...),
    "Little Dragon Nanny": CardData(card_id='Little Dragon Nanny', name='Little Dragon Nanny', ...),
    "Whitescale Herald": CardData(card_id='Whitescale Herald', name='Whitescale Herald', ...),
    "Calamity Breath": CardData(card_id='Calamity Breath', name='Calamity Breath', ...),
    "Kit, Luxfang Champion": CardData(card_id='Kit, Luxfang Champion', name='Kit, Luxfang Champion', ...),
    "Eyfa, Windrider": CardData(card_id='Eyfa, Windrider', name='Eyfa, Windrider', ...),
    "Zell, Windreader": CardData(card_id='Zell, Windreader', name='Zell, Windreader', ...),
    "Marion, Ravishing Dragonewt": CardData(card_id='Marion, Ravishing Dragonewt', name='Marion, Ravishing Dragonewt', ...),
    "Goldennote Melody": CardData(card_id='Goldennote Melody', name='Goldennote Melody', ...),
    "Genesis Dragon Reborn": CardData(card_id='Genesis Dragon Reborn', name='Genesis Dragon Reborn', ...),
    "Liu Feng, Goldennote Ward": CardData(card_id='Liu Feng, Goldennote Ward', name='Liu Feng, Goldennote Ward', ...),
    "Zahar, Stormwave Dragoon": CardData(card_id='Zahar, Stormwave Dragoon', name='Zahar, Stormwave Dragoon', ...),
    "Twilight Dragon": CardData(card_id='Twilight Dragon', name='Twilight Dragon', ...),
    "Fan of Otohime": CardData(card_id='Fan of Otohime', name='Fan of Otohime', ...),
    "Burnite, Anathema of Flame": CardData(card_id='Burnite, Anathema of Flame', name='Burnite, Anathema of Flame', ...),
    "Forte, Blackwing Dragoon": CardData(card_id='Forte, Blackwing Dragoon', name='Forte, Blackwing Dragoon', ...),
    "Garyu, Fabled Dragonkin": CardData(card_id='Garyu, Fabled Dragonkin', name='Garyu, Fabled Dragonkin', ...),
    "Aryll, Moonstruck Vampire": CardData(card_id='Aryll, Moonstruck Vampire', name='Aryll, Moonstruck Vampire', ...),
    "Nameless Demon": CardData(card_id='Nameless Demon', name='Nameless Demon', ...),
    "Little Miss Bonemancer": CardData(card_id='Little Miss Bonemancer', name='Little Miss Bonemancer', ...),
    "Ghost Juggler": CardData(card_id='Ghost Juggler', name='Ghost Juggler', ...),
    "Darkseal Demon": CardData(card_id='Darkseal Demon', name='Darkseal Demon', ...),
    "Reaper's Deathslash": CardData(card_id='Reaper's Deathslash', name='Reaper's Deathslash', ...),
    "Mino, Shrewd Reaper": CardData(card_id='Mino, Shrewd Reaper', name='Mino, Shrewd Reaper', ...),
    "Beryl, Nightmare Incarnate": CardData(card_id='Beryl, Nightmare Incarnate', name='Beryl, Nightmare Incarnate', ...),
    "Yuna, Occult Hunter": CardData(card_id='Yuna, Occult Hunter', name='Yuna, Occult Hunter', ...),
    "Vlad, Impaler": CardData(card_id='Vlad, Impaler', name='Vlad, Impaler', ...),
    "Shadowcrypt Memorial": CardData(card_id='Shadowcrypt Memorial', name='Shadowcrypt Memorial', ...),
    "Ceres, Blue Rose Maiden": CardData(card_id='Ceres, Blue Rose Maiden', name='Ceres, Blue Rose Maiden', ...),
    "Orthrus, Hellhound Blader": CardData(card_id='Orthrus, Hellhound Blader', name='Orthrus, Hellhound Blader', ...),
    "Mukan, Shadowcrypt Ward": CardData(card_id='Mukan, Shadowcrypt Ward', name='Mukan, Shadowcrypt Ward', ...),
    "Balto, Dusk Bounty Hunter": CardData(card_id='Balto, Dusk Bounty Hunter', name='Balto, Dusk Bounty Hunter', ...),
    "Rage of Serpents": CardData(card_id='Rage of Serpents', name='Rage of Serpents', ...),
    "Cerberus, Hellfire Unleashed": CardData(card_id='Cerberus, Hellfire Unleashed', name='Cerberus, Hellfire Unleashed', ...),
    "Medusa, Venomfang Royalty": CardData(card_id='Medusa, Venomfang Royalty', name='Medusa, Venomfang Royalty', ...),
    "Aragavy, Eternal Hunter": CardData(card_id='Aragavy, Eternal Hunter', name='Aragavy, Eternal Hunter', ...),
    "Angelic Prism Priestess": CardData(card_id='Angelic Prism Priestess', name='Angelic Prism Priestess', ...),
    "Holy Shieldmaiden": CardData(card_id='Holy Shieldmaiden', name='Holy Shieldmaiden', ...),
    "Radiant Guiding Angel": CardData(card_id='Radiant Guiding Angel', name='Radiant Guiding Angel', ...),
    "Mainyu, Darkdweller": CardData(card_id='Mainyu, Darkdweller', name='Mainyu, Darkdweller', ...),
    "Serene Sanctuary": CardData(card_id='Serene Sanctuary', name='Serene Sanctuary', ...),
    "Featherfall": CardData(card_id='Featherfall', name='Featherfall', ...),
    "Sarissa, Luxspear Al-mi'raj": CardData(card_id='Sarissa, Luxspear Al-mi'raj', name='Sarissa, Luxspear Al-mi'raj', ...),
    "Reno, Luxwing Featherfolk": CardData(card_id='Reno, Luxwing Featherfolk', name='Reno, Luxwing Featherfolk', ...),
    "Maeve, Guardian of Earth": CardData(card_id='Maeve, Guardian of Earth', name='Maeve, Guardian of Earth', ...),
    "Darkhaven Grace": CardData(card_id='Darkhaven Grace', name='Darkhaven Grace', ...),
    "Dose of Holiness": CardData(card_id='Dose of Holiness', name='Dose of Holiness', ...),
    "Skullfane of Demise": CardData(card_id='Skullfane of Demise', name='Skullfane of Demise', ...),
    "Ronavero, Darkhaven Ward": CardData(card_id='Ronavero, Darkhaven Ward', name='Ronavero, Darkhaven Ward', ...),
    "Lapis, Shining Seraph": CardData(card_id='Lapis, Shining Seraph', name='Lapis, Shining Seraph', ...),
    "Pact of the Beast Princess": CardData(card_id='Pact of the Beast Princess', name='Pact of the Beast Princess', ...),
    "Unholy Vessel": CardData(card_id='Unholy Vessel', name='Unholy Vessel', ...),
    "Rodeo, Anathema of Judgment": CardData(card_id='Rodeo, Anathema of Judgment', name='Rodeo, Anathema of Judgment', ...),
    "Jeanne, Saintly Knight": CardData(card_id='Jeanne, Saintly Knight', name='Jeanne, Saintly Knight', ...),
    "Salefa, Guardian of Water": CardData(card_id='Salefa, Guardian of Water', name='Salefa, Guardian of Water', ...),
    "Elise, Electrifying Inventor": CardData(card_id='Elise, Electrifying Inventor', name='Elise, Electrifying Inventor', ...),
    "Dirk, Metal Mercenary": CardData(card_id='Dirk, Metal Mercenary', name='Dirk, Metal Mercenary', ...),
    "Ironheart Hunter": CardData(card_id='Ironheart Hunter', name='Ironheart Hunter', ...),
    "Medical-Grade Assassin": CardData(card_id='Medical-Grade Assassin', name='Medical-Grade Assassin', ...),
    "Puppet Shield": CardData(card_id='Puppet Shield', name='Puppet Shield', ...),
    "Artifact Recharge": CardData(card_id='Artifact Recharge', name='Artifact Recharge', ...),
    "Rukina, Resistance Leader": CardData(card_id='Rukina, Resistance Leader', name='Rukina, Resistance Leader', ...),
    "Lovestruck Puppeteer": CardData(card_id='Lovestruck Puppeteer', name='Lovestruck Puppeteer', ...),
    "Noah, Thread of Death": CardData(card_id='Noah, Thread of Death', name='Noah, Thread of Death', ...),
    "Stream of Life": CardData(card_id='Stream of Life', name='Stream of Life', ...),
    "Doomwright Resurgence": CardData(card_id='Doomwright Resurgence', name='Doomwright Resurgence', ...),
    "Miriam, the Resolute": CardData(card_id='Miriam, the Resolute', name='Miriam, the Resolute', ...),
    "Sylvia, Garden Executioner": CardData(card_id='Sylvia, Garden Executioner', name='Sylvia, Garden Executioner', ...),
    "Liam, Crazed Creator": CardData(card_id='Liam, Crazed Creator', name='Liam, Crazed Creator', ...),
    "Alouette, Doomwright Ward": CardData(card_id='Alouette, Doomwright Ward', name='Alouette, Doomwright Ward', ...),
    "Ancient Cannon": CardData(card_id='Ancient Cannon', name='Ancient Cannon', ...),
    "Eudie, Maiden Reborn": CardData(card_id='Eudie, Maiden Reborn', name='Eudie, Maiden Reborn', ...),
    "Orchis, Newfound Heart": CardData(card_id='Orchis, Newfound Heart', name='Orchis, Newfound Heart', ...),
    "Ralmia, Sonic Boom": CardData(card_id='Ralmia, Sonic Boom', name='Ralmia, Sonic Boom', ...),
}

TOKEN_CARD_DATABASE = {
    "Goblin": CardData(card_id='Goblin', name='Goblin', ...),
    "Silent Rider": CardData(card_id='Silent Rider', name='Silent Rider', ...),
    "Servant of Cocytus": CardData(card_id='Servant of Cocytus', name='Servant of Cocytus', ...),
    "Demon of Purgatory": CardData(card_id='Demon of Purgatory', name='Demon of Purgatory', ...),
    "Astaroth's Reckoning": CardData(card_id='Astaroth's Reckoning', name='Astaroth's Reckoning', ...),
    "Fairy": CardData(card_id='Fairy', name='Fairy', ...),
    "Deepwood Bounty": CardData(card_id='Deepwood Bounty', name='Deepwood Bounty', ...),
    "Bramble Burst": CardData(card_id='Bramble Burst', name='Bramble Burst', ...),
    "Knight": CardData(card_id='Knight', name='Knight', ...),
    "Steelclad Knight": CardData(card_id='Steelclad Knight', name='Steelclad Knight', ...),
    "Clay Golem": CardData(card_id='Clay Golem', name='Clay Golem', ...),
    "Guardian Golem": CardData(card_id='Guardian Golem', name='Guardian Golem', ...),
    "Paper Shikigami": CardData(card_id='Paper Shikigami', name='Paper Shikigami', ...),
    "Demonic Shikigami": CardData(card_id='Demonic Shikigami', name='Demonic Shikigami', ...),
    "Magic Sediment": CardData(card_id='Magic Sediment', name='Magic Sediment', ...),
    "Looking Smart!": CardData(card_id='Looking Smart!', name='Looking Smart!', ...),
    "Celestial Shikigami": CardData(card_id='Celestial Shikigami', name='Celestial Shikigami', ...),
    "Noble Shikigami": CardData(card_id='Noble Shikigami', name='Noble Shikigami', ...),
    "Anne's Summoning": CardData(card_id='Anne's Summoning', name='Anne's Summoning', ...),
    "Fire Drake Whelp": CardData(card_id='Fire Drake Whelp', name='Fire Drake Whelp', ...),
    "Vastwing Dragon": CardData(card_id='Vastwing Dragon', name='Vastwing Dragon', ...),
    "Otohime's Bodyguard": CardData(card_id='Otohime's Bodyguard', name='Otohime's Bodyguard', ...),
    "Supreme Golden Dragon": CardData(card_id='Supreme Golden Dragon', name='Supreme Golden Dragon', ...),
    "Supreme Silver Dragon": CardData(card_id='Supreme Silver Dragon', name='Supreme Silver Dragon', ...),
    "Skeleton": CardData(card_id='Skeleton', name='Skeleton', ...),
    "Bat": CardData(card_id='Bat', name='Bat', ...),
    "Ghost": CardData(card_id='Ghost', name='Ghost', ...),
    "Mimi, Right Paw Hellhound": CardData(card_id='Mimi, Right Paw Hellhound', name='Mimi, Right Paw Hellhound', ...),
    "Coco, Left Paw Hellhound": CardData(card_id='Coco, Left Paw Hellhound', name='Coco, Left Paw Hellhound', ...),
    "Holy Falcon": CardData(card_id='Holy Falcon', name='Holy Falcon', ...),
    "Holyflame Tiger": CardData(card_id='Holyflame Tiger', name='Holyflame Tiger', ...),
    "Regal Falcon": CardData(card_id='Regal Falcon', name='Regal Falcon', ...),
    "Puppet": CardData(card_id='Puppet', name='Puppet', ...),
    "Enhanced Puppet": CardData(card_id='Enhanced Puppet', name='Enhanced Puppet', ...),
    "Gear of Ambition": CardData(card_id='Gear of Ambition', name='Gear of Ambition', ...),
    "Gear of Remembrance": CardData(card_id='Gear of Remembrance', name='Gear of Remembrance', ...),
    "Striker Artifact": CardData(card_id='Striker Artifact', name='Striker Artifact', ...),
    "Fortifier Artifact": CardData(card_id='Fortifier Artifact', name='Fortifier Artifact', ...),
    "Ominous Artifact α": CardData(card_id='Ominous Artifact α', name='Ominous Artifact α', ...),
    "Ominous Artifact β": CardData(card_id='Ominous Artifact β', name='Ominous Artifact β', ...),
    "Ominous Artifact γ": CardData(card_id='Ominous Artifact γ', name='Ominous Artifact γ', ...),
    "Masterwork Artifact Ω": CardData(card_id='Masterwork Artifact Ω', name='Masterwork Artifact Ω', ...),
    "Lloyd": CardData(card_id='Lloyd', name='Lloyd', ...),
}

